name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: RPI_deployment

    steps:
      - uses: actions/checkout@v3

      - name: Install cloudflared
        run: |
          sudo mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg \
            | sudo tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' \
            | sudo tee /etc/apt/sources.list.d/cloudflared.list
          sudo apt-get update
          sudo apt-get install -y cloudflared

      - name: Setup Cloudflare Access cert + token
        run: |
          mkdir -p ~/.cloudflared
          echo "${{ secrets.CF_CERT_PEM }}" > ~/.cloudflared/cert.pem
          chmod 600 ~/.cloudflared/cert.pem

          cat <<EOF > ~/.cloudflared/token.yml
          tunnel_token: null
          ingress:
            - service: ssh://localhost:22
          credentials:
            client_id: "${{ secrets.CF_CLIENT_ID }}"
            client_secret: "${{ secrets.CF_CLIENT_SECRET }}"
          EOF

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          cat <<EOF > ~/.ssh/config
          Host raspi
            HostName ssh.mrajczyk.dev
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/id_ed25519
            StrictHostKeyChecking no
            UserKnownHostsFile /dev/null
            ProxyCommand cloudflared access ssh \
              --hostname %h \
              --service-token-id "${{ secrets.CF_CLIENT_ID }}" \
              --service-token-secret "${{ secrets.CF_CLIENT_SECRET }}"
          EOF
          chmod 600 ~/.ssh/config

      - name: Test SSH
        run: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null raspi "echo 'Connected via Cloudflare Access SSH from GitHub!'"

      - name: Primitive deployment
        run: |
          ssh raspi << 'EOF'
            set -e

            cd /home/mrajczyk/Desktop/dev/test/MRajczykDEV
            git pull
            npm i
            npm run build

            sudo rsync -a --delete \
              /home/mrajczyk/Desktop/dev/test/MRajczykDEV/dist/ \
              /var/www/mrajczyk/
          EOF
